---
id: cndf2023
base_name: slide
tags: ['quic', 'aws', 'gcp']
presentation_date: '2023-08-03'
presentation_start_time:
presentation_end_time:
version: 1.0.1
licenses: ['MIT']
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
author:
  markup_language: :rd
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
source_code_url: https://github.com/unasuke/cndf2023
